### ISSUE TITLE
建议给出修改样例

### ISSUE THREAD

**Issue by ChangQingAAS** [iShareStuff/ZoteroTheme#2]
<img width="105" alt="image" src="https://user-images.githubusercontent.com/74063075/198765758-be07f98b-e656-4c51-b698-deb7c2ee4690.png">
希望能给出各个组成部件都在zotero哪个部位的示意图，这样方便用户自定义颜色。
因为有的用户不是专门做前端的，有些名词可能不太懂，自己探索使用有一点点慢。
谢谢！

**Comment by Arti-Ir** [comment]
https://www.bilibili.com/video/BV1B34y1e7F2/?vd_source=3cd3fe8bd6f1aa1e48d76d1ab0e3e638

**Comment by Arti-Ir** [comment]
无情猛男粉
![image](https://user-images.githubusercontent.com/112146304/207209900-fd850658-456e-4bfa-be19-8eb41fb70781.png)
夏日炫冰蓝
![image](https://user-images.githubusercontent.com/112146304/207210071-7c9ca336-17a6-47c5-b469-94d1ede0cb89.png)
配色网站：
https://encycolorpedia.cn/deeadc
